apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 9.4.14
    helm:
      values: |
        server:
          service:
            type: NodePort
            nodePortHttp: 30080
            nodePortHttps: 30443
          extraArgs:
            - --insecure
        configs:
          params:
            server.insecure: true
          secret:
            argocdServerAdminPassword: "$2b$12$QFfBa6BwnB6wE7YE1xToouXbAkKsgn8aPjTS890r7eiPO1GYoheOy"
        dex:
          enabled: false
        notifications:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
